auto-labels:
  docs:
    - README.md
    - docs/**
    - docs_src/**
    - examples/**
    - mkdocs.yml
    - overrides/**
  internal:
    - .github/**
    - scripts/**
    - .gitignore
    - .pre-commit-config.yaml
    - uv.lock
